### ISSUE TITLE
RGB值与截屏后获取的RGB值不一样

### ISSUE THREAD

**Issue by yuyedaidao** [wangzhili0803/pixScanner#1]
没看到你的联系方式，所以只能提个ISSUE了，想问问兄弟有没有遇到通过这种方式获取的RGB值与通过截屏后用工具测的RGB值不一样的问题

**Comment by jk08039527** [comment]
这种场景我倒是没有用到过。我调试的时候打开了开发者选项里的“指针位置”，然后触点的坐标和像素点的坐标应该也是对应的。如果是不一样的话，你可以看看是不是坐标没对上导致的
