### ISSUE TITLE
reader 赋值

### ISSUE THREAD

**Issue by chenyuanbo23** [wangzhili0803/pixScanner#2]
static ImageReader reader;
    private static Bitmap bitmap;

    /**
     * 获取目标点的RGB值
     */
    public static int getColor(int x, int y) {
        if (reader == null) {
            LogUtils.d("reader is null");
            return -1;
        }

小白初学，有个问题请教一下，我每次走到这里因为 reader=null 就直接return了，请问这个 ImageReader  reader是如何赋值的
![rgb](https://user-images.githubusercontent.com/116791519/198215858-ac39aacc-760a-4a56-9599-c59185c23b73.jpg)

**Comment by jk08039527** [comment]
赋值在MainActicity里通过MediaProjectionManager 初始化出来 ，你在onActivityResult方法中调试一下看看有什么错误信息
